package generator;

import lombok.Data;

import java.io.Serializable;

/**
 * null
 * @TableName users
 */
@Data
public class Users implements Serializable {
    /**
     * 
     *
     * @mbg.generated 2021-03-05 16:40:12
     */
    private Integer id;

    /**
     * 账号。登陆用
     *
     * @mbg.generated 2021-03-05 16:40:12
     */
    private String account;

    /**
     * 密码
     *
     * @mbg.generated 2021-03-05 16:40:12
     */
    private String password;

    /**
     * 名称
     *
     * @mbg.generated 2021-03-05 16:40:12
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table users
     *
     * @mbg.generated 2021-03-05 16:40:12
     */
    private static final long serialVersionUID = 1L;
}