package com.lcz.wdf.entity;

import java.io.Serializable;
import lombok.Data;

/**
 * null
 * @TableName permission
 */
@Data
public class Permission implements Serializable {
    /**
     * 
     *
     * @mbg.generated 2021-03-16 14:18:21
     */
    private Integer id;

    /**
     * 角色id
     *
     * @mbg.generated 2021-03-16 14:18:21
     */
    private Integer roleId;

    /**
     * 权限
     *
     * @mbg.generated 2021-03-16 14:18:21
     */
    private String permission;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table permission
     *
     * @mbg.generated 2021-03-16 14:18:21
     */
    private static final long serialVersionUID = 1L;
}