package com.lcz.wdf.entity;

import java.io.Serializable;
import java.util.Date;
import lombok.Data;

/**
 * null
 * @TableName role
 */
@Data
public class Role implements Serializable {
    /**
     * 
     *
     * @mbg.generated 2021-03-16 10:57:53
     */
    private Integer id;

    /**
     * 
     *
     * @mbg.generated 2021-03-16 10:57:53
     */
    private String name;

    /**
     * 角色类型：1表示超管，2表示管理员，3表示用户定义的角色
     *
     * @mbg.generated 2021-03-16 10:57:53
     */
    private Integer type;

    /**
     * 创建人身份证号码
     *
     * @mbg.generated 2021-03-16 10:57:53
     */
    private String creatorIdNumber;

    /**
     * 创建人姓名
     *
     * @mbg.generated 2021-03-16 10:57:53
     */
    private String creatorName;

    /**
     * 创建人部门编号
     *
     * @mbg.generated 2021-03-16 10:57:53
     */
    private String creatorDepartmentId;

    /**
     * 创建人部门名称
     *
     * @mbg.generated 2021-03-16 10:57:53
     */
    private String creatorDepartmentName;

    /**
     * 修改时间
     *
     * @mbg.generated 2021-03-16 10:57:53
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table role
     *
     * @mbg.generated 2021-03-16 10:57:53
     */
    private static final long serialVersionUID = 1L;
}